name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        contexts : [backend, frontend ]
        include:
          - contexts: backend
            dockerfile: ./backend/Dockerfile.prod
            image: rsvispo/economviz
          - contexts: frontend
            dockerfile: ./frontend/Dockerfile.prod
            image: rsvispo/economviz

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ matrix.image }} 
        
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./${{ matrix.contexts }}
        file: ${{ matrix.dockerfile }}
        push: true
        tags: rsvispo/economviz:${{ matrix.contexts }}
        labels: ${{ steps.meta.outputs.labels }}

  update-ssh:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: ./runUpdate.sh


